version: "2"
services:
  ec2-opener:
    build:
      context: ../..
      dockerfile: environment/dev/Dockerfile
    volumes:
      - ../..:/go/src/github.com/slok/ec2-opener/
      - ~/.bash_history.ec2-opener:/home/app/.bash_history
    command: "go run main.go"
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
